# TCL File Generated by Component Editor 18.1
# Sat Dec 07 13:26:06 CET 2024
# DO NOT MODIFY


# 
# avalon_telemetre "avalon_telemetre" v1.0
#  2024.12.07.13:26:06
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_telemetre
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_telemetre
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_telemetre
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL telemetre_us_Avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file telemetre_us_avalon.vhd VHDL PATH ../src/telemetre_us_avalon.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset Reset_n
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 Read_n read_n Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point telemetre
# 
add_interface telemetre conduit end
set_interface_property telemetre associatedClock clock
set_interface_property telemetre associatedReset ""
set_interface_property telemetre ENABLED true
set_interface_property telemetre EXPORT_OF ""
set_interface_property telemetre PORT_NAME_MAP ""
set_interface_property telemetre CMSIS_SVD_VARIABLES ""
set_interface_property telemetre SVD_ADDRESS_GROUP ""

add_interface_port telemetre trig trig Output 1
add_interface_port telemetre echo echo Input 1
add_interface_port telemetre Dist_cm distance Output 10


# 
# connection point Reset_n
# 
add_interface Reset_n reset end
set_interface_property Reset_n associatedClock clock
set_interface_property Reset_n synchronousEdges DEASSERT
set_interface_property Reset_n ENABLED true
set_interface_property Reset_n EXPORT_OF ""
set_interface_property Reset_n PORT_NAME_MAP ""
set_interface_property Reset_n CMSIS_SVD_VARIABLES ""
set_interface_property Reset_n SVD_ADDRESS_GROUP ""

add_interface_port Reset_n rst_n reset_n Input 1

